### ISSUE TITLE
What if the data becomes outdated?

### ISSUE THREAD

**Issue by wouldnt** [joeymalvinni/is-tor#1]
What are you going to do if the data becomes obsolete, are you just going to abandon it so people keep using the data used by your module?

**Comment by joeymalvinni** [comment]
@wouldnt Good question. Currently, this module is not in use enough to warrant any concerns, but in the long run I was thinking of setting up a solution where the .txt file is updated with the list from the [bulk list](https://check.torproject.org/torbulkexitlist) when the official list is updated.

If you have any ideas or would be willing to work on this, I would be happy to accept the PR.

**Comment by joeymalvinni** [comment]
Additionally, the format used in the exit nodes list (locally) is JSON, and not a txt file, which may lead to some conversion issues with something like Github actions. However, since my experience with Github actions is limited, I cannot say for sure.

**Comment by wouldnt** [comment]
> If you have any ideas or would be willing to work on this, I would be happy to accept the PR.

@joeymalvinni 
I have no prior experience with GitHub Actions however I will look into it and see if I can come up with a potential solution, also would this not require pushing a new release to NPM as well? Not fully in the loop of publishing to NPM either so I don't really know.

**Comment by joeymalvinni** [comment]
Also, because the data will probably only be updated every day (at least that's the amount of accuracy the project requires at the moment) by the tor maintainers, we should relieve the Github bot (and Tor servers) by only updating every day. This also reduces the spam commits.
